---
- name: Playbook to install kubeadm,kubelet and kubectl
  hosts:
    - master
    - slave
  become: yes
  tasks:
    - name: Copy shell script to target
      copy:
        src: /home/ubuntu/ansible/both_node.sh
        dest: /home/ubuntu/both_node.sh
        mode: '0755'

    - name: Execute shell script
      shell: /home/ubuntu/both_node.sh
      register: result
    

    - name: Show the output of the script
      debug:
        var: result
    
