---
- name: Run shell script on target
  hosts: jenkins
  become: yes
  tasks:
    - name: Copy shell script to target
      copy:
        src: /home/ubuntu/ansible/java-script.sh
        dest: /tmp/java-script.sh
        mode: '0755'

    - name: Execute shell script
      shell: /tmp/java-script.sh
      register: result
    

    - name: Show the output of the script
      debug:
        var: result

