---
- name: Run shell script on target
  hosts: jenkins
  become: yes
  tasks:
    - name: Copy shell script to target
      copy:
        src: /home/ubuntu/ansible/jenkins-script.sh
        dest: /tmp/script.sh
        mode: '0755'

    - name: Execute shell script
      shell: /tmp/script.sh
      register: result
    

    - name: Show the output of the script
      debug:
        var: result

